### ISSUE TITLE
Missleading docs for compressor options

### ISSUE THREAD

**Issue by Robbilie** [mongodb-js/mongodb-core#264]
`http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#.connect`

The client takes an option called compression, the description might be a bit missleading as it looks like its supposed to be a string. But instead of this:
```
{
  compression: "snappy"
}
```
it has to be this:
```
{
  compression: {
    compressors: ["snappy"]
  }
}
```

**Comment by Robbilie** [comment]
Why was this closed...?

**Comment by mbroadst** [comment]
Hi @Robbilie. This project has been merged into the main driver, and will soon be outright deprecated. GitHub issues have never been our primary form of ticketing (I'm sure you ended up on this project because GitHub issues were not enabled on `node-mongodb-native`). I've opened a JIRA ticket for you [here](https://jira.mongodb.org/browse/NODE-2037), please track that for progress on your issue. For further issues, please open a JIRA ticket.

**Comment by Robbilie** [comment]
Thanks, appreciate it :)
